version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - run:
          name: Clone k/website repo
          command: |
            mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
            git clone git@github.com:kubernetes/website.git
      
      - run:
          name: List out all Indonesian translated pages
          command: |
            pushd website

            echo "List of translated pages:"
            echo ""
            find ./content/id/docs -type f | grep -v index.md

            echo ""
            echo "Translated pages count:"
            find ./content/id/docs -type f | grep -v index.md | wc -l

            popd

      - run:
          name: List of open PRs for language/id
          command: |
            curl -s https://api.github.com/search/issues\?q\=is:open+type:pr+label:language/id\&sort\=created\&order\=dsc > tmp
            cat tmp | jq -r '.items[] | "\(.user.login)\n\(.title)\n\(.html_url)\n"'

      - checkout

      - run:
          name: Find diff between EN and ID docs
          command: sig-docs-id/scripts/diff_en_id.py website
