version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - run:
          name: Clone k/website repo
          command: |
            mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
            git clone git@github.com:kubernetes/website.git
      
      - run:
          name: List out all Indonesian translated pages
          command: |
            pushd website

            echo "List of translated pages:"
            echo ""
            find ./content/id/docs -type f | grep -v index.md

            echo ""
            echo "Translated pages count:"
            find ./content/id/docs -type f | grep -v index.md | wc -l

            popd

      - run:
          name: List of open PRs
          command: |
            pushd website

            sudo python3 -m pip install -r ./scripts/requirements.txt

            echo "List of pages that have been touched by open PRs:"
            echo ""
            find ./content/en/docs -type f | sed 's#/en/#/id/#g' | xargs -L1 ./scripts/find_pr.py --tags "language/id" $1 --token $GITHUB_API_TOKEN

            popd
