version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - run:
          name: clone k/website repo
          command: |
            mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
            git clone git@github.com:kubernetes/website.git
      
      - run:
          name: list out all Indonesian translated pages
          command: |
            pages=$(find content/id/docs -type f)
            echo $pages
            echo ""

            num_translated=$(echo $pages | grep -v _index.md | wc -l)
            echo "translated pages count: $num_translated"
